import { Metadata } from "next";

export const aismMetadata: Metadata = {
    title: 'American International School of Medicine | A Leading Global Medical Institution',
    description: "Pursue world-class medical education with U.S. clinical rotations and a supportive community. Start your journey today—apply now!",
    keywords: [
        "medical school",
        "international medical school",
        "physician training",
        "global healthcare",
        "medical education",
        "clinical rotations",
        "research opportunities",
        "student body diversity",
        "competitive residency programs",
        "AISM",
        "American International School of Medicine",
        "medical degree",
        "MD program",
        "doctor of medicine",
        "healthcare career",
        "medical licensing",
        "medical board exams",
        "medical school admissions",
        "medical school requirements",
        "medical school application",
        "medical school tuition",
        "medical school financial aid",
        "medical school scholarships",
        "medical school curriculum",
        "medical school courses",
        "medical school faculty",
        "medical school staff",
        "medical school facilities",
        "medical school campus",
        "medical school library",
        "medical school technology",
        "medical school student life",
        "medical school clubs",
        "medical school organizations",
        "medical school events",
        "medical school community",
        "medical school ethics",
        "medical school professionalism",
        "medical school leadership",
        "medical school service",
        "medical school research",
        "medical school publications",
        "medical school presentations",
        "medical school conferences",
        "medical school internships",
        "medical school externships",
        "medical school electives",
        "medical school clinical experiences",
        "medical school patient care",
        "medical school patient interaction",
        "medical school communication skills",
        "medical school teamwork skills",
        "medical school problem-solving skills",
        "medical school critical thinking skills",
        "medical school cultural competence",
        "medical school global health",
        "medical school humanitarian work",
        "medical school volunteerism",
        "medical school diversity and inclusion",
        "medical school equity",
        "medical school social justice",
        "medical school advocacy",
        "medical school policy",
        "medical school leadership",
        "medical school innovation",
        "medical school entrepreneurship",
        "medical school technology",
        "medical school artificial intelligence",
        "medical school machine learning",
        "medical school big data",
        "medical school digital health",
        "medical school telehealth",
        "medical school telemedicine",
        "medical school virtual reality",
        "medical school augmented reality",
        "medical school future of medicine",
        "medical school career paths",
        "medical school job opportunities",
        "medical school salary",
        "medical school work-life balance",
        "medical school stress management",
        "medical school mental health",
        "medical school well-being",
        "medical school support services",
        "medical school counseling",
        "medical school tutoring",
        "medical school mentoring",
        "medical school academic advising",
        "medical school student success",
        "medical school accreditation",
        "medical school licensing",
        "medical school certification",
        "medical school quality assurance",
        "medical school patient safety",
        "medical school evidence-based medicine",
        "medical school clinical research",
        "medical school translational research",
        "medical school population health",
        "medical school public health",
        "medical school global health",
        "medical school health disparities",
        "medical school health equity",
        "medical school health policy",
        "medical school health systems",
        "medical school healthcare delivery",
        "medical school healthcare management",
        "medical school healthcare administration",
        "medical school healthcare finance",
        "medical school healthcare ethics",
        "medical school healthcare law",
        "medical school healthcare policy",
        "medical school healthcare reform",
        "medical school healthcare innovation",
        "medical school healthcare technology",
        "medical school healthcare future",
        "medical school career opportunities",
        "medical school job market",
        "medical school salary",
        "medical school work-life balance",
        "medical school stress management",
        "medical school mental health",
        "medical school well-being",
        "medical school support services",
        "medical school counseling",
        "medical school tutoring",
        "medical school mentoring",
        "medical school academic advising",
        "medical school student success",
        "medical school accreditation",
        "medical school licensing",
        "medical school certification",
        "medical school quality",
        'AISM medical school',
        'international medical school',
        'medical education',
        'study medicine in Guyana',
        'clinical rotations in USA',
        'medical degree abroad',
        'healthcare education',
        'pre-medical programs',
        'basic sciences courses',
        'clinical sciences courses',
        'global medical careers',
        'medical research',
        'medical residency',
        'become a doctor',
        'MD programs',
        'Caribbean medical school',
        'medical school admission',
        'American International School of Medicine Guyana',
        'AISM global medical opportunities',
        'study medicine internationally',
        'medical career pathways',
        'physician training programs',
        'medical school faculty',
        'medical student success',
        'Guyana medical school',
        'clinical rotations AISM',
        'medical student admissions process',
        'AISM scholarships',
        'AISM campus life',
        'medical school Guyana',
        'AISM medical curriculum',
        'international health education',
        'AISM faculty',
        'student life at AISM',
        'medical student rotations USA',
        'AISM admission requirements'
    ],
    authors: [{ name: "AISM", url: "https://aism.edu/" }, { name: "Fabiconcept", url: "https://fabiconcept.online" }],
    creator: 'Dr. Colin Wilkinson MPH', 
    openGraph: {
        title: 'American International School of Medicine | A Leading Global Medical Institution',
        description: "Pursue world-class medical education with U.S. clinical rotations and a supportive community. Start your journey today—apply now!",
        url: 'https://aism.edu/',
        locale: 'en_US',
        images: [
            {
                url: 'https://aism.edu/images/aism-campus.jpg',  // Replace with an actual AISM image
                width: 1200,
                height: 800,
                alt: 'AISM Campus in Guyana',
            },
        ],
    },
    twitter: {
        card: 'summary_large_image',
        title: 'Study Medicine at AISM | Global Medical Training',
        description: 'Pursue world-class medical education with U.S. clinical rotations and a supportive community. Start your journey today—apply now!',
        images: ['https://aism.edu/images/aism-campus-twitter.jpg'],
    },
    icons: {
        icon: 'https://aism-edu.sirv.com/icons/android-icon-192x192.png',
        shortcut: 'https://aism-edu.sirv.com/icons/ms-icon-310x310.png',
        apple: 'https://aism-edu.sirv.com/icons/ms-icon-310x310.png',
        other: {
            rel: 'https://aism-edu.sirv.com/icons/favicon.ico',
            url: 'https://aism-edu.sirv.com/icons/favicon.ico',
        },
    },
    robots: {
        index: true,
        follow: true,
        nocache: true,
        googleBot: {
            index: true,
            follow: true,
            noimageindex: false,
            'max-video-preview': -1,
            'max-image-preview': 'large',
            'max-snippet': -1,
        },
    },
};
